-- Health and Fitness Tables Creation Script
-- Generated: 2025-04-07 01:24:18 (UTC)
-- Generated by: wilmer2000

-- hlthappUserFeedback
CREATE TABLE IF NOT EXISTS "hlthappUserFeedback"
(
    uid          TEXT,
    did          TEXT,
    contact      TEXT,
    ip           TEXT,
    platform     TEXT,
    ua           TEXT,
    version_name TEXT,
    version_code TEXT,
    model        TEXT,
    tags         TEXT,
    content      TEXT,
    create_time  TIMESTAMP,
    update_time  TIMESTAMP
);

-- hlth_center_aggregated_fitness_data
CREATE TABLE IF NOT EXISTS "hlth_center_aggregated_fitness_data"
(
    uid         TEXT,
    sid         TEXT,
    tag         TEXT,
    key         TEXT,
    time        TIMESTAMP,
    update_time TIMESTAMP,
    value       TEXT
);

-- hlth_center_data_source
CREATE TABLE IF NOT EXISTS "hlth_center_data_source"
(
    uid         TEXT,
    sid         TEXT,
    identifier  TEXT,
    model       TEXT,
    name        TEXT,
    alias       TEXT,
    status      TEXT,
    create_time TIMESTAMP,
    update_time TIMESTAMP
);

-- hlth_center_fitness_data
CREATE TABLE IF NOT EXISTS "hlth_center_fitness_data"
(
    uid         TEXT,
    sid         TEXT,
    key         TEXT,
    time        TIMESTAMP,
    uptime_data TIMESTAMP,
    value       TEXT
);

-- hlth_center_sport_record
CREATE TABLE IF NOT EXISTS "hlth_center_sport_record"
(
    uid         TEXT,
    sid         TEXT,
    categroy    TEXT,
    key         TEXT,
    time        TIMESTAMP,
    update_time TIMESTAMP,
    value       TEXT
);

-- user_device_setting
CREATE TABLE IF NOT EXISTS "user_device_setting"
(
    uid         TEXT,
    did         TEXT,
    module      TEXT,
    key         TEXT,
    create_time TIMESTAMP,
    update_time TIMESTAMP,
    value       TEXT
);

-- user_fitness_data_records
CREATE TABLE IF NOT EXISTS "user_fitness_data_records"
(
    uid         TEXT,
    did         TEXT,
    tag         TEXT,
    key         TEXT,
    time        TIMESTAMP,
    last_modify TIMESTAMP,
    metric      TEXT,
    value       TEXT
);

-- user_fitness_profile
CREATE TABLE IF NOT EXISTS "user_fitness_profile"
(
    uid               TEXT,
    vo2_max           NUMERIC,
    maximal_met       NUMERIC,
    max_hrm           INTEGER,
    min_hrm           INTEGER,
    record_max_hrm    INTEGER,
    daily_cal_goal    INTEGER,
    daily_step_goal   INTEGER,
    initial_weight    NUMERIC,
    child_auth        TEXT,
    initial_time      TIMESTAMP,
    daily_stand_goal  INTEGER,
    daily_sleep_goal  INTERVAL,
    regular_goal_list TEXT
);

-- user_fitness_with_uuid_data_records
CREATE TABLE IF NOT EXISTS "user_fitness_with_uuid_data_records"
(
    uid         TEXT,
    did         TEXT,
    tag         TEXT,
    key         TEXT,
    record_id   TEXT,
    time        TIMESTAMP,
    last_modify TIMESTAMP,
    value       TEXT
);

-- user_health_plan_records
CREATE TABLE IF NOT EXISTS "user_health_plan_records"
(
    uid         TEXT,
    plan_type   TEXT,
    status      TEXT,
    timestamp   TIMESTAMP,
    last_modify TIMESTAMP,
    "desc"      TEXT,
    plan_info   TEXT,
    value       TEXT
);

-- user_pk_invite_record
CREATE TABLE IF NOT EXISTS "user_pk_invite_record"
(
    id         TEXT,
    inviter    TEXT,
    invitee    TEXT,
    pkid       TEXT,
    pktype     TEXT,
    istatus    TEXT,
    zoneoffset TEXT,
    ctime      TIMESTAMP,
    utime      TIMESTAMP
);

-- user_pk_record
CREATE TABLE IF NOT EXISTS "user_pk_record"
(
    uid              TEXT,
    pkuid            TEXT,
    pkid             TEXT,
    pktype           TEXT,
    pkstatus         TEXT,
    pkuidprivacy     BOOLEAN,
    pkstarttime      TIMESTAMP,
    pkendtime        TIMESTAMP,
    userzoneoffset   TEXT,
    pkuserzoneoffset TEXT,
    pkscore          TEXT,
    pksettletime     TIMESTAMP,
    pkresult         TEXT,
    ctime            TIMESTAMP,
    utime            TIMESTAMP
);

-- user_pk_result_statistics
CREATE TABLE IF NOT EXISTS "user_pk_result_statistics"
(
    uid              TEXT,
    id               TEXT,
    pkuid            TEXT,
    statisticsresult TEXT,
    ctime            TIMESTAMP,
    utime            TIMESTAMP
);

-- Add appropriate indexes
-- CREATE INDEX IF NOT EXISTS idx_hlthappUserFeedback_user_id ON "hlthappUserFeedback" (user_id);
-- CREATE INDEX IF NOT EXISTS idx_hlth_center_aggregated_fitness_data_user_id_date ON "hlth_center_aggregated_fitness_data" (user_id, date);
-- CREATE INDEX IF NOT EXISTS idx_hlth_center_fitness_data_user_id_type ON "hlth_center_fitness_data" (user_id, data_type);
-- CREATE INDEX IF NOT EXISTS idx_hlth_center_sport_record_user_id ON "hlth_center_sport_record" (user_id);
-- CREATE INDEX IF NOT EXISTS idx_user_fitness_data_records_user_id_date ON "user_fitness_data_records" (user_id, record_date);
-- CREATE INDEX IF NOT EXISTS idx_user_fitness_with_uuid_user_id_type ON "user_fitness_with_uuid_data_records" (user_id, data_type);
-- CREATE INDEX IF NOT EXISTS idx_user_health_plan_records_user_id ON "user_health_plan_records" (user_id);
-- CREATE INDEX IF NOT EXISTS idx_user_pk_record_pk_id ON "user_pk_record" (pk_id);
-- CREATE INDEX IF NOT EXISTS idx_user_pk_result_statistics_pk_id ON "user_pk_result_statistics" (pk_id);